spring:
  jpa:
   hibernate:
    ddl-auto: create
   show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/idat_ecfinal
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
